---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: openvas-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  nfs:
    path: /opt/openvas/data
    server: 192.168.0.140
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openvas-pvc
spec:
  resources:
    requests:
      storage: 10Gi
  accessModes:
  - ReadWriteOnce
