apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: openvas
  name: openvas
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 443
    nodePort: 30002
    name: user
  - port: 9390
    protocol: TCP
    targetPort: 9390
    nodePort: 30003
    name: admin
  selector:
    app: openvas
  type: NodePort
status:
  loadBalancer: {}
